version: "3.8"
services:
    master:
        hostname: es01
        container_name: es01
        image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
        ports:
            - 9200
        networks:
            - elastic
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
            - ELASTIC_PASSWORD=elastic
    kibana:
        hostname: kibana
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:${ES_VERSION}
        ports:
            - 5601:5601
        networks:
            - elastic

networks:
    elastic:
        
        